name: ar_face
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<2
  - pytorch
  - torchvision
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - pip
  - pip:
      - mediapipe==0.10.14
      - opencv-python
      - transformers
      - datasets
      - huggingface_hub
      - wandb
      - tensorboard
      - einops
      - timm
